packages:
  - apps/*
  - packages/*

allowBuilds:
  "@swc/core": true
  bcrypt: true
  cpu-features: false
  esbuild: true
  node-pty: false
  sharp: false
  ssh2: true
  unrs-resolver: false

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - bcrypt
  - cpu-features
  - esbuild
  - node-pty
  - sharp
  - ssh2
  - unrs-resolver
