# Docker Compose overlay for using Docker secrets
# Usage: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up

secrets:
  AUTH_SECRET:
    file: ./.secrets/AUTH_SECRET
  encryption_key:
    file: ./.secrets/encryption_key
  jwt_secret:
    file: ./.secrets/jwt_secret
  internal_api_key:
    file: ./.secrets/internal_api_key
  postgres_password:
    file: ./.secrets/postgres_password

services:
  postgres:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

  runtime-api:
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - jwt_secret

  orchestrator:
    environment:
      API_KEY_FILE: /run/secrets/internal_api_key
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - internal_api_key
      - jwt_secret

  cronium-app:
    environment:
      AUTH_SECRET_FILE: /run/secrets/AUTH_SECRET
      ENCRYPTION_KEY_FILE: /run/secrets/encryption_key
      INTERNAL_API_KEY_FILE: /run/secrets/internal_api_key
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - AUTH_SECRET
      - encryption_key
      - internal_api_key
      - jwt_secret

  websocket:
    secrets:
      - postgres_password
