groups:
  - name: cronium_alerts
    interval: 30s
    rules:
      # Service health alerts
      - alert: ServiceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

      # Runtime API alerts
      - alert: RuntimeAPIHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="runtime-api"}[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Runtime API latency is high"
          description: "95th percentile latency is above 500ms (current: {{ $value }}s)"

      - alert: RuntimeAPIErrorRate
        expr: rate(http_requests_total{job="runtime-api",status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Runtime API error rate is high"
          description: "Error rate is above 10% (current: {{ $value }})"

      # Orchestrator alerts
      - alert: OrchestratorJobQueueBacklog
        expr: job_queue_size{job="orchestrator"} > 100
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Job queue backlog is growing"
          description: "More than 100 jobs in queue for 10 minutes (current: {{ $value }})"

      - alert: OrchestratorHighMemoryUsage
        expr: process_resident_memory_bytes{job="orchestrator"} / 1024 / 1024 > 1024
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Orchestrator memory usage is high"
          description: "Memory usage is above 1GB (current: {{ $value }}MB)"

      # Database alerts
      - alert: DatabaseConnectionPoolExhausted
        expr: pg_stat_database_numbackends{datname="cronium"} / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Using more than 80% of available connections"

      - alert: DatabaseSlowQueries
        expr: rate(pg_stat_statements_mean_time_seconds{datname="cronium"}[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Database queries are slow"
          description: "Average query time is above 1 second"

      # Cache alerts
      - alert: ValkeyHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Valkey memory usage is high"
          description: "Using more than 90% of available memory"

      - alert: ValkeyConnectionsHigh
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many Valkey connections"
          description: "More than 100 connected clients (current: {{ $value }})"

      # Application alerts
      - alert: HighJobFailureRate
        expr: rate(job_status_total{status="failed"}[15m]) / rate(job_status_total[15m]) > 0.1
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: "High job failure rate"
          description: "More than 10% of jobs are failing (current: {{ $value }})"

      - alert: LongRunningJobs
        expr: job_duration_seconds{quantile="0.95"} > 300
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Jobs taking too long to complete"
          description: "95th percentile job duration is above 5 minutes"
