import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    // Next.js sets NODE_ENV itself (dev/build/start); processes launched
    // outside the Next CLI (e.g. the socket server via tsx) may not have it.
    // Never set NODE_ENV in env/.env* files — see the note there.
    NODE_ENV: z
      .enum(["development", "test", "production"])
      .default("development"),
    AUTH_SECRET: z
      .string()
      .min(
        32,
        "AUTH_SECRET must be at least 32 characters (openssl rand -hex 32)",
      ),
    AUTH_URL: z.string().url(),
    SMTP_HOST: z.string().optional(),
    SMTP_PORT: z.string().optional(),
    SMTP_USER: z.string().optional(),
    SMTP_PASSWORD: z.string().optional(),
    SMTP_FROM_EMAIL: z.string().optional(),
    DATABASE_URL: z.string(),
    OPENAI_API_KEY: z.string().optional(),
    // OAuth apps for tool integrations (e.g. Google Sheets)
    OAUTH_GOOGLE_CLIENT_ID: z.string().optional(),
    OAUTH_GOOGLE_CLIENT_SECRET: z.string().optional(),
    OAUTH_MICROSOFT_CLIENT_ID: z.string().optional(),
    OAUTH_MICROSOFT_CLIENT_SECRET: z.string().optional(),
    OAUTH_MICROSOFT_TENANT_ID: z.string().optional(),
    OAUTH_SLACK_CLIENT_ID: z.string().optional(),
    OAUTH_SLACK_CLIENT_SECRET: z.string().optional(),
    PUBLIC_APP_URL: z.string().url().optional(),
    ENCRYPTION_KEY: z
      .string()
      .regex(
        /^[0-9a-fA-F]{64}$/,
        "ENCRYPTION_KEY must be exactly 64 hex characters (openssl rand -hex 32)",
      ),
    ORCHESTRATOR_URL: z
      .string()
      .url()
      .optional()
      .default("http://orchestrator:8080"),
    VALKEY_URL: z.string().optional(),
    REDIS_URL: z.string().optional(),
    SOCKET_INTERNAL_URL: z.string().url().optional(),
    // Number of trusted reverse-proxy hops in front of the app. The client IP
    // is taken this many entries from the right of X-Forwarded-For, so an
    // attacker cannot spoof their source IP by prepending header values.
    // 0 (default) means no trusted proxy: forwarding headers are ignored and
    // the direct socket peer is used. Set to 1 behind a single TLS proxy.
    TRUSTED_PROXY_HOPS: z.coerce.number().int().min(0).max(10).default(0),
    // SHA-256 hex hash of the one-time first-admin bootstrap token generated by
    // the installer. When set, creating the first admin requires the matching
    // plaintext token. Absent in local/dev installs (setup then needs no token).
    BOOTSTRAP_TOKEN_HASH: z
      .string()
      .regex(/^[0-9a-fA-F]{64}$/)
      .optional(),
    // Require Admin accounts to have TOTP MFA enabled before performing
    // admin-privileged operations. Defaults to enforced in production and
    // relaxed in development (so the dev auto-admin isn't blocked). Set
    // explicitly to "true"/"false" to override.
    CRONIUM_ENFORCE_ADMIN_MFA: z.enum(["true", "false"]).optional(),
  },
  client: {
    PUBLIC_APP_URL: z.string().url(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_URL: process.env.AUTH_URL,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASSWORD: process.env.SMTP_PASSWORD,
    SMTP_FROM_EMAIL: process.env.SMTP_FROM_EMAIL,
    DATABASE_URL: process.env.DATABASE_URL,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    OAUTH_GOOGLE_CLIENT_ID: process.env.OAUTH_GOOGLE_CLIENT_ID,
    OAUTH_GOOGLE_CLIENT_SECRET: process.env.OAUTH_GOOGLE_CLIENT_SECRET,
    OAUTH_MICROSOFT_CLIENT_ID: process.env.OAUTH_MICROSOFT_CLIENT_ID,
    OAUTH_MICROSOFT_CLIENT_SECRET: process.env.OAUTH_MICROSOFT_CLIENT_SECRET,
    OAUTH_MICROSOFT_TENANT_ID: process.env.OAUTH_MICROSOFT_TENANT_ID,
    OAUTH_SLACK_CLIENT_ID: process.env.OAUTH_SLACK_CLIENT_ID,
    OAUTH_SLACK_CLIENT_SECRET: process.env.OAUTH_SLACK_CLIENT_SECRET,
    PUBLIC_APP_URL: process.env.PUBLIC_APP_URL,
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
    ORCHESTRATOR_URL: process.env.ORCHESTRATOR_URL,
    VALKEY_URL: process.env.VALKEY_URL,
    REDIS_URL: process.env.REDIS_URL,
    SOCKET_INTERNAL_URL: process.env.SOCKET_INTERNAL_URL,
    TRUSTED_PROXY_HOPS: process.env.TRUSTED_PROXY_HOPS,
    BOOTSTRAP_TOKEN_HASH: process.env.BOOTSTRAP_TOKEN_HASH,
    CRONIUM_ENFORCE_ADMIN_MFA: process.env.CRONIUM_ENFORCE_ADMIN_MFA,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
