package executor

import (
	"archive/tar"
	"bufio"
	"bytes"
	"compress/gzip"
	"crypto"
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha512"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"github.com/addison-moore/cronium/apps/runner/cronium-runner/internal/payload"
	"github.com/addison-moore/cronium/apps/runner/cronium-runner/pkg/types"
	"github.com/sirupsen/logrus"
)

const (
	signalChildEnv   = "CRONIUM_RUNNER_TEST_SIGNAL_CHILD"
	signalWorkDirEnv = "CRONIUM_RUNNER_TEST_SIGNAL_WORKDIR"
)

// TestMain re-execs the test binary as a small helper process for the signal
// handling test (setupSignalHandling calls os.Exit, so it cannot be exercised
// in-process).
func TestMain(m *testing.M) {
	if os.Getenv(signalChildEnv) == "1" {
		signalChildMain()
		return
	}
	os.Exit(m.Run())
}

// signalChildMain registers the executor's signal handler with a work
// directory and blocks until the handler terminates the process.
func signalChildMain() {
	log := logrus.New()
	log.SetOutput(io.Discard)
	e := New(log)
	e.workDir = os.Getenv(signalWorkDirEnv)
	e.setupSignalHandling()
	fmt.Println("READY")
	select {}
}

// logRecord is a captured logrus entry.
type logRecord struct {
	level   logrus.Level
	message string
	fields  map[string]interface{}
}

// captureHook records every log entry so tests can assert on streamed output.
type captureHook struct {
	mu      sync.Mutex
	records []logRecord
}

func (h *captureHook) Levels() []logrus.Level { return logrus.AllLevels }

func (h *captureHook) Fire(e *logrus.Entry) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	fields := make(map[string]interface{}, len(e.Data))
	for k, v := range e.Data {
		fields[k] = v
	}
	h.records = append(h.records, logRecord{level: e.Level, message: e.Message, fields: fields})
	return nil
}

// streamLines returns the messages logged for one output stream, in order.
func (h *captureHook) streamLines(stream string) []string {
	h.mu.Lock()
	defer h.mu.Unlock()
	var out []string
	for _, r := range h.records {
		if r.fields["stream"] == stream {
			out = append(out, r.message)
		}
	}
	return out
}

func (h *captureHook) hasMessageContaining(substr string) bool {
	h.mu.Lock()
	defer h.mu.Unlock()
	for _, r := range h.records {
		if strings.Contains(r.message, substr) {
			return true
		}
	}
	return false
}

func (h *captureHook) findField(message, field string) (interface{}, bool) {
	h.mu.Lock()
	defer h.mu.Unlock()
	for _, r := range h.records {
		if r.message == message {
			v, ok := r.fields[field]
			return v, ok
		}
	}
	return nil, false
}

func newTestExecutor(t *testing.T) (*Executor, *captureHook) {
	t.Helper()
	hook := &captureHook{}
	log := logrus.New()
	log.SetOutput(io.Discard)
	log.SetLevel(logrus.DebugLevel)
	log.AddHook(hook)
	return New(log), hook
}

func requireTool(t *testing.T, name string) {
	t.Helper()
	if _, err := exec.LookPath(name); err != nil {
		t.Skipf("%s not available on this host; the %s interpreter path needs it", name, name)
	}
}

// setupScript prepares a work dir with a stub discovery script (the real one
// is generated by SetupHelpers) plus the entrypoint, and returns an executor
// wired to run it via executeScript.
func setupScript(t *testing.T, interpreter types.ScriptType, entrypoint, script string) (*Executor, *captureHook) {
	t.Helper()
	e, hook := newTestExecutor(t)
	workDir := t.TempDir()
	croniumDir := filepath.Join(workDir, ".cronium")
	if err := os.MkdirAll(croniumDir, 0o755); err != nil {
		t.Fatalf("failed to create .cronium dir: %v", err)
	}
	stubs := map[string]string{
		"discovery.sh": "#!/bin/bash\n",
		"discovery.py": "",
		"discovery.js": "",
	}
	for name, content := range stubs {
		if err := os.WriteFile(filepath.Join(croniumDir, name), []byte(content), 0o755); err != nil {
			t.Fatalf("failed to write %s stub: %v", name, err)
		}
	}
	if script != "" {
		if err := os.WriteFile(filepath.Join(workDir, entrypoint), []byte(script), 0o755); err != nil {
			t.Fatalf("failed to write entrypoint: %v", err)
		}
	}
	e.workDir = workDir
	e.manifest = &types.Manifest{
		Version:     "v1",
		Interpreter: interpreter,
		Entrypoint:  entrypoint,
	}
	return e, hook
}

// runWithWatchdog runs executeScript and fails fast if it does not return —
// the regression mode of the long-line bug was an indefinite hang.
func runWithWatchdog(t *testing.T, e *Executor, timeout time.Duration) error {
	t.Helper()
	done := make(chan error, 1)
	go func() { done <- e.executeScript() }()
	select {
	case err := <-done:
		return err
	case <-time.After(timeout):
		t.Fatalf("executeScript did not return within %v (hung child process?)", timeout)
		return nil
	}
}

func TestExecuteScriptExitZeroCapturesBothStreams(t *testing.T) {
	requireTool(t, "bash")
	e, hook := setupScript(t, types.ScriptTypeBash, "script.sh", `
echo out-line-1
echo out-line-2
echo err-line-1 1>&2
`)

	if err := runWithWatchdog(t, e, 10*time.Second); err != nil {
		t.Fatalf("expected exit 0, got: %v", err)
	}

	stdout := hook.streamLines("stdout")
	// Per-stream ordering is pinned; interleaving across streams is not
	// deterministic (two goroutines) and deliberately not asserted.
	want := []string{"out-line-1", "out-line-2"}
	if len(stdout) != len(want) || stdout[0] != want[0] || stdout[1] != want[1] {
		t.Errorf("stdout lines = %#v, want %#v", stdout, want)
	}
	stderr := hook.streamLines("stderr")
	if len(stderr) != 1 || stderr[0] != "err-line-1" {
		t.Errorf("stderr lines = %#v, want [err-line-1]", stderr)
	}
}

func TestExecuteScriptNonZeroExitReported(t *testing.T) {
	requireTool(t, "bash")
	e, hook := setupScript(t, types.ScriptTypeBash, "script.sh", "exit 7\n")

	err := runWithWatchdog(t, e, 10*time.Second)
	if err == nil || !strings.Contains(err.Error(), "script exited with code 7") {
		t.Fatalf("expected exit-code-7 error, got: %v", err)
	}
	if code, ok := hook.findField("Script exited with non-zero status", "exit_code"); !ok || code != 7 {
		t.Errorf("exit_code log field = %v (present=%v), want 7", code, ok)
	}
}

func TestExecuteScriptUnsupportedInterpreter(t *testing.T) {
	e, _ := setupScript(t, types.ScriptType("RUBY"), "script.rb", "puts 1\n")
	err := e.executeScript()
	if err == nil || !strings.Contains(err.Error(), "unsupported interpreter: RUBY") {
		t.Fatalf("expected unsupported-interpreter error, got: %v", err)
	}
}

func TestExecuteScriptRejectsTraversalEntrypoint(t *testing.T) {
	e, _ := setupScript(t, types.ScriptTypeBash, "script.sh", "true\n")
	e.manifest.Entrypoint = "../outside.sh"
	err := e.executeScript()
	if err == nil || !strings.Contains(err.Error(), "invalid entrypoint") {
		t.Fatalf("expected invalid-entrypoint error, got: %v", err)
	}
}

func TestExecuteScriptMissingEntrypoint(t *testing.T) {
	e, _ := setupScript(t, types.ScriptTypeBash, "missing.sh", "")
	err := e.executeScript()
	if err == nil || !strings.Contains(err.Error(), "invalid entrypoint") {
		t.Fatalf("expected invalid-entrypoint error for missing file, got: %v", err)
	}
}

func TestExecuteScriptEnvironmentPropagation(t *testing.T) {
	requireTool(t, "bash")
	t.Setenv("CRONIUM_JOB_ID", "")
	t.Setenv("CRONIUM_EXECUTION_ID", "exec-from-env")
	t.Setenv("CRONIUM_HELPER_MODE", "bundled")
	t.Setenv("CRONIUM_API_ENDPOINT", "http://127.0.0.1:1/api")
	t.Setenv("CRONIUM_API_TOKEN", "secret-token")
	t.Setenv("PARENT_VAR", "from-parent")

	e, hook := setupScript(t, types.ScriptTypeBash, "script.sh", `
echo "MANIFEST_VAR=$MANIFEST_VAR"
echo "PARENT_VAR=$PARENT_VAR"
echo "CRONIUM_JOB_ID=$CRONIUM_JOB_ID"
echo "CRONIUM_EVENT_ID=$CRONIUM_EVENT_ID"
echo "CRONIUM_EXECUTION_ID=$CRONIUM_EXECUTION_ID"
echo "CRONIUM_WORK_DIR=$CRONIUM_WORK_DIR"
echo "CRONIUM_HELPER_MODE=$CRONIUM_HELPER_MODE"
echo "CRONIUM_API_ENDPOINT=$CRONIUM_API_ENDPOINT"
echo "CRONIUM_API_TOKEN=$CRONIUM_API_TOKEN"
`)
	e.manifest.Environment = map[string]string{
		"MANIFEST_VAR": "from-manifest",
		// Manifest entries are appended after os.Environ(); os/exec keeps the
		// last duplicate, so the manifest value must win.
		"PARENT_VAR": "manifest-wins",
	}
	e.manifest.Metadata = types.Metadata{
		JobID:       "job-1",
		EventID:     "ev-1",
		ExecutionID: "exec-from-manifest", // must lose to the env var
	}

	if err := runWithWatchdog(t, e, 10*time.Second); err != nil {
		t.Fatalf("script failed: %v", err)
	}

	got := hook.streamLines("stdout")
	want := []string{
		"MANIFEST_VAR=from-manifest",
		"PARENT_VAR=manifest-wins",
		"CRONIUM_JOB_ID=job-1",
		"CRONIUM_EVENT_ID=ev-1",
		"CRONIUM_EXECUTION_ID=exec-from-env",
		"CRONIUM_WORK_DIR=" + e.workDir,
		"CRONIUM_HELPER_MODE=bundled",
		"CRONIUM_API_ENDPOINT=http://127.0.0.1:1/api",
		"CRONIUM_API_TOKEN=secret-token",
	}
	for _, line := range want {
		found := false
		for _, g := range got {
			if g == line {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("child environment missing %q; stdout = %#v", line, got)
		}
	}
}

func TestExecuteScriptJobIDFallsBackToParentEnv(t *testing.T) {
	requireTool(t, "bash")
	t.Setenv("CRONIUM_JOB_ID", "job-from-parent")

	e, hook := setupScript(t, types.ScriptTypeBash, "script.sh",
		"echo \"CRONIUM_JOB_ID=$CRONIUM_JOB_ID\"\n")
	e.manifest.Metadata = types.Metadata{EventID: "ev-1"} // no JobID in manifest

	if err := runWithWatchdog(t, e, 10*time.Second); err != nil {
		t.Fatalf("script failed: %v", err)
	}
	stdout := hook.streamLines("stdout")
	if len(stdout) != 1 || stdout[0] != "CRONIUM_JOB_ID=job-from-parent" {
		t.Errorf("stdout = %#v, want CRONIUM_JOB_ID=job-from-parent", stdout)
	}
}

func TestExecuteScriptExecutionIDFromManifestWhenEnvUnset(t *testing.T) {
	requireTool(t, "bash")
	t.Setenv("CRONIUM_EXECUTION_ID", "")

	e, hook := setupScript(t, types.ScriptTypeBash, "script.sh",
		"echo \"CRONIUM_EXECUTION_ID=$CRONIUM_EXECUTION_ID\"\n")
	e.manifest.Metadata = types.Metadata{EventID: "ev-1", ExecutionID: "exec-from-manifest"}

	if err := runWithWatchdog(t, e, 10*time.Second); err != nil {
		t.Fatalf("script failed: %v", err)
	}
	stdout := hook.streamLines("stdout")
	if len(stdout) != 1 || stdout[0] != "CRONIUM_EXECUTION_ID=exec-from-manifest" {
		t.Errorf("stdout = %#v, want manifest execution ID", stdout)
	}
}

// Regression test for the long-line hang: a 200 KB line exceeded the old
// default 64 KB bufio.Scanner limit; scanning aborted, nobody drained the
// pipe, the child blocked in write(2), and cmd.Wait() never returned. With
// the enlarged buffer the line is captured intact and the run completes.
func TestExecuteScriptLongLineDoesNotHang(t *testing.T) {
	requireTool(t, "bash")
	e, hook := setupScript(t, types.ScriptTypeBash, "script.sh", `
head -c 200000 /dev/zero | tr '\0' 'a'
echo
echo after-long-line
`)

	if err := runWithWatchdog(t, e, 15*time.Second); err != nil {
		t.Fatalf("script failed: %v", err)
	}

	stdout := hook.streamLines("stdout")
	if len(stdout) != 2 {
		t.Fatalf("stdout line count = %d, want 2 (long line + marker)", len(stdout))
	}
	if len(stdout[0]) != 200000 || strings.Trim(stdout[0], "a") != "" {
		t.Errorf("long line corrupted: len=%d", len(stdout[0]))
	}
	if stdout[1] != "after-long-line" {
		t.Errorf("marker line = %q, want after-long-line", stdout[1])
	}
}

// Pin the over-limit policy: a single line larger than maxLogLineBytes aborts
// line scanning for that stream — a read error is logged, the remainder of
// the stream (including anything after the giant line) is drained unlogged —
// but the child still runs to completion and its exit status is honored.
func TestExecuteScriptOverlongLineIsDroppedNotHung(t *testing.T) {
	requireTool(t, "bash")
	overlong := maxLogLineBytes + 512*1024 // 1.5 MiB > 1 MiB cap
	e, hook := setupScript(t, types.ScriptTypeBash, "script.sh", fmt.Sprintf(`
head -c %d /dev/zero | tr '\0' 'b'
echo
echo trailing-line
`, overlong))

	if err := runWithWatchdog(t, e, 15*time.Second); err != nil {
		t.Fatalf("expected exit 0 despite dropped output, got: %v", err)
	}

	if lines := hook.streamLines("stdout"); len(lines) != 0 {
		t.Errorf("expected no stdout lines after over-long token, got %d", len(lines))
	}
	if !hook.hasMessageContaining("Error reading stdout stream") {
		t.Error("expected a logged read error for the over-long stdout line")
	}
}

func TestExecuteScriptPythonInterpreter(t *testing.T) {
	requireTool(t, "python3")
	e, hook := setupScript(t, types.ScriptTypePython, "script.py", "print(\"python-out\")\n")
	if err := runWithWatchdog(t, e, 15*time.Second); err != nil {
		t.Fatalf("python script failed: %v", err)
	}
	stdout := hook.streamLines("stdout")
	if len(stdout) != 1 || stdout[0] != "python-out" {
		t.Errorf("stdout = %#v, want [python-out]", stdout)
	}
}

func TestExecuteScriptNodeInterpreter(t *testing.T) {
	requireTool(t, "node")
	e, hook := setupScript(t, types.ScriptTypeNode, "script.js", "console.log('node-out');\n")
	if err := runWithWatchdog(t, e, 15*time.Second); err != nil {
		t.Fatalf("node script failed: %v", err)
	}
	stdout := hook.streamLines("stdout")
	if len(stdout) != 1 || stdout[0] != "node-out" {
		t.Errorf("stdout = %#v, want [node-out]", stdout)
	}
}

func TestCleanupRemovesWorkDirOnceAndIsIdempotent(t *testing.T) {
	e, _ := newTestExecutor(t)
	// payload.Cleanup only removes directories carrying the extraction marker.
	workDir := filepath.Join(t.TempDir(), "cronium-run-test")
	if err := os.MkdirAll(filepath.Join(workDir, "sub"), 0o755); err != nil {
		t.Fatalf("failed to create work dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(workDir, "sub", "f"), []byte("x"), 0o644); err != nil {
		t.Fatalf("failed to write file: %v", err)
	}
	e.workDir = workDir

	if err := e.Cleanup(); err != nil {
		t.Fatalf("Cleanup failed: %v", err)
	}
	if _, err := os.Stat(workDir); !os.IsNotExist(err) {
		t.Errorf("work dir still exists after Cleanup (stat err: %v)", err)
	}
	// Second call is a no-op.
	if err := e.Cleanup(); err != nil {
		t.Errorf("second Cleanup should be a no-op, got: %v", err)
	}
}

func TestCleanupNoWorkDirIsNoop(t *testing.T) {
	e, _ := newTestExecutor(t)
	if err := e.Cleanup(); err != nil {
		t.Fatalf("Cleanup with no work dir should be nil, got: %v", err)
	}
}

// The cleanup path refuses to delete directories that do not look like
// runner extraction dirs — a guard against deleting arbitrary paths.
func TestCleanupRefusesForeignDirectory(t *testing.T) {
	e, _ := newTestExecutor(t)
	dir := t.TempDir()
	e.workDir = dir

	err := e.Cleanup()
	if err == nil || !strings.Contains(err.Error(), "invalid directory for cleanup") {
		t.Fatalf("expected cleanup guard error, got: %v", err)
	}
	if _, statErr := os.Stat(dir); statErr != nil {
		t.Errorf("directory should not have been removed: %v", statErr)
	}
}

// SIGTERM must clean up the extracted work dir and exit with code 1, and the
// process must actually die (no zombie left waiting).
func TestSignalHandlerCleansUpAndExits(t *testing.T) {
	workDir := filepath.Join(t.TempDir(), "cronium-run-signal")
	if err := os.MkdirAll(workDir, 0o755); err != nil {
		t.Fatalf("failed to create work dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(workDir, "marker"), []byte("x"), 0o644); err != nil {
		t.Fatalf("failed to write marker: %v", err)
	}

	cmd := exec.Command(os.Args[0])
	cmd.Env = append(os.Environ(), signalChildEnv+"=1", signalWorkDirEnv+"="+workDir)
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		t.Fatalf("failed to get stdout pipe: %v", err)
	}
	if err := cmd.Start(); err != nil {
		t.Fatalf("failed to start child: %v", err)
	}
	defer func() { _ = cmd.Process.Kill() }() // safety net on test failure

	// Wait for the child to signal that its handler is registered.
	readyCh := make(chan error, 1)
	go func() {
		scanner := bufio.NewScanner(stdout)
		for scanner.Scan() {
			if scanner.Text() == "READY" {
				readyCh <- nil
				return
			}
		}
		readyCh <- fmt.Errorf("child exited before READY: %v", scanner.Err())
	}()
	select {
	case err := <-readyCh:
		if err != nil {
			t.Fatalf("child never became ready: %v", err)
		}
	case <-time.After(10 * time.Second):
		t.Fatal("timed out waiting for child READY")
	}

	if err := cmd.Process.Signal(syscall.SIGTERM); err != nil {
		t.Fatalf("failed to send SIGTERM: %v", err)
	}

	waitCh := make(chan error, 1)
	go func() { waitCh <- cmd.Wait() }()
	select {
	case err := <-waitCh:
		exitErr, ok := err.(*exec.ExitError)
		if !ok {
			t.Fatalf("expected non-zero exit after SIGTERM, got: %v", err)
		}
		if code := exitErr.ExitCode(); code != 1 {
			t.Errorf("exit code = %d, want 1", code)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("child did not exit promptly after SIGTERM")
	}

	if _, err := os.Stat(workDir); !os.IsNotExist(err) {
		t.Errorf("work dir was not cleaned up on SIGTERM (stat err: %v)", err)
	}
}

// --- Execute() end-to-end -----------------------------------------------

type tarEntry struct {
	name    string
	content string
	mode    int64
}

// writeSignedPayload builds a tar.gz payload from entries, signs it the same
// way the orchestrator does (Ed25519ph over the SHA-512 digest), and points
// CRONIUM_VERIFY_KEY at the matching public key.
func writeSignedPayload(t *testing.T, entries []tarEntry) string {
	t.Helper()

	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gz)
	for _, e := range entries {
		if err := tw.WriteHeader(&tar.Header{
			Name:     e.name,
			Mode:     e.mode,
			Size:     int64(len(e.content)),
			Typeflag: tar.TypeReg,
		}); err != nil {
			t.Fatalf("failed to write tar header: %v", err)
		}
		if _, err := tw.Write([]byte(e.content)); err != nil {
			t.Fatalf("failed to write tar content: %v", err)
		}
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("failed to close tar: %v", err)
	}
	if err := gz.Close(); err != nil {
		t.Fatalf("failed to close gzip: %v", err)
	}

	return signPayloadBytes(t, buf.Bytes())
}

// signPayloadBytes writes content as the payload file, signs it, and sets
// CRONIUM_VERIFY_KEY. Returns the payload path.
func signPayloadBytes(t *testing.T, content []byte) string {
	t.Helper()
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("failed to generate key: %v", err)
	}
	payloadPath := filepath.Join(t.TempDir(), "payload.tar.gz")
	if err := os.WriteFile(payloadPath, content, 0o644); err != nil {
		t.Fatalf("failed to write payload: %v", err)
	}
	digest := sha512.Sum512(content)
	sig, err := priv.Sign(rand.Reader, digest[:], crypto.SHA512)
	if err != nil {
		t.Fatalf("failed to sign payload: %v", err)
	}
	if err := os.WriteFile(payloadPath+".sig", []byte(base64.StdEncoding.EncodeToString(sig)+"\n"), 0o644); err != nil {
		t.Fatalf("failed to write signature: %v", err)
	}
	t.Setenv(payload.VerifyKeyEnvVar, base64.StdEncoding.EncodeToString(pub))
	return payloadPath
}

// pinCroniumEnv snapshots (and restores) the env vars Execute/SetupHelpers
// mutate, so end-to-end runs cannot leak state into other tests.
func pinCroniumEnv(t *testing.T) {
	t.Helper()
	for _, k := range []string{
		"PATH", "CRONIUM_HELPER_MODE", "CRONIUM_EXECUTION_ID", "CRONIUM_JOB_ID",
		"CRONIUM_EVENT_ID", "CRONIUM_WORK_DIR", "CRONIUM_API_ENDPOINT", "CRONIUM_API_TOKEN",
	} {
		t.Setenv(k, os.Getenv(k))
	}
}

const e2eManifest = `version: v1
interpreter: bash
entrypoint: script.sh
environment:
  E2E_VAR: e2e-value
metadata:
  jobId: job-e2e
  eventId: ev-e2e
  eventVersion: 1
  createdAt: 2026-01-02T03:04:05Z
  executionId: exec-e2e
  eventName: E2E Event
  trigger: manual
`

func TestExecuteFailsClosedWithoutVerifyKey(t *testing.T) {
	e, _ := newTestExecutor(t)
	t.Setenv(payload.VerifyKeyEnvVar, "")

	err := e.Execute(filepath.Join(t.TempDir(), "payload.tar.gz"))
	if err == nil || !strings.Contains(err.Error(), "payload verification failed") {
		t.Fatalf("expected fail-closed verification error, got: %v", err)
	}
}

func TestExecuteRejectsCorruptArchive(t *testing.T) {
	e, _ := newTestExecutor(t)
	payloadPath := signPayloadBytes(t, []byte("this is not a gzip stream"))

	err := e.Execute(payloadPath)
	if err == nil || !strings.Contains(err.Error(), "failed to extract payload") {
		t.Fatalf("expected extraction error, got: %v", err)
	}
}

func TestExecuteMissingManifest(t *testing.T) {
	e, _ := newTestExecutor(t)
	t.Cleanup(func() { _ = e.Cleanup() })
	payloadPath := writeSignedPayload(t, []tarEntry{
		{name: "script.sh", content: "echo hi\n", mode: 0o755},
	})

	err := e.Execute(payloadPath)
	if err == nil || !strings.Contains(err.Error(), "failed to find manifest") {
		t.Fatalf("expected missing-manifest error, got: %v", err)
	}
}

func TestExecuteInvalidManifest(t *testing.T) {
	e, _ := newTestExecutor(t)
	t.Cleanup(func() { _ = e.Cleanup() })
	payloadPath := writeSignedPayload(t, []tarEntry{
		{name: "manifest.yaml", content: "version: v1\ninterpreter: bash\n", mode: 0o644},
		{name: "script.sh", content: "echo hi\n", mode: 0o755},
	})

	err := e.Execute(payloadPath)
	if err == nil || !strings.Contains(err.Error(), "failed to parse manifest") {
		t.Fatalf("expected manifest parse error, got: %v", err)
	}
}

// Full pipeline: verify -> extract -> manifest -> helper setup -> execute ->
// collect output -> cleanup. Requires the embedded Linux helper binaries, so
// it runs on Linux CI and is skipped elsewhere.
func TestExecuteEndToEndBash(t *testing.T) {
	if !helperBinariesEmbedded() {
		t.Skip("embedded helper binaries exist only for linux/amd64 and linux/arm64 (embed.go); SetupHelpers cannot succeed on this host")
	}
	requireTool(t, "bash")
	pinCroniumEnv(t)
	t.Setenv("CRONIUM_EXECUTION_ID", "exec-e2e")

	e, hook := newTestExecutor(t)
	t.Cleanup(func() { _ = e.Cleanup() })
	payloadPath := writeSignedPayload(t, []tarEntry{
		{name: "manifest.yaml", content: e2eManifest, mode: 0o644},
		{name: "script.sh", content: `
echo "hello-from-payload E2E_VAR=$E2E_VAR"
echo '{"msg":"hi"}' | cronium.output
`, mode: 0o755},
	})

	if err := e.Execute(payloadPath); err != nil {
		t.Fatalf("Execute failed: %v", err)
	}

	found := false
	for _, line := range hook.streamLines("stdout") {
		if line == "hello-from-payload E2E_VAR=e2e-value" {
			found = true
		}
	}
	if !found {
		t.Errorf("script output not streamed; stdout = %#v", hook.streamLines("stdout"))
	}

	// Bundled-mode scaffolding was materialized in the work dir.
	croniumDir := filepath.Join(e.workDir, ".cronium")
	for _, f := range []string{"config.json", "context.json", "variables.json", "discovery.sh",
		filepath.Join("bin", "cronium.output")} {
		if _, err := os.Stat(filepath.Join(croniumDir, f)); err != nil {
			t.Errorf("expected %s in work dir: %v", f, err)
		}
	}

	// The helper binary wrote the script's output for collection.
	outputJSON, err := os.ReadFile(filepath.Join(croniumDir, "output.json"))
	if err != nil {
		t.Fatalf("cronium.output did not write output.json: %v", err)
	}
	if !strings.Contains(string(outputJSON), `"msg": "hi"`) {
		t.Errorf("output.json = %s, want data msg=hi", outputJSON)
	}
	if !hook.hasMessageContaining("Collected helper output") {
		t.Error("expected Execute to log collected helper output")
	}

	// Cleanup removes the extraction dir.
	workDir := e.workDir
	if err := e.Cleanup(); err != nil {
		t.Fatalf("Cleanup failed: %v", err)
	}
	if _, err := os.Stat(workDir); !os.IsNotExist(err) {
		t.Errorf("work dir still exists after Cleanup (stat err: %v)", err)
	}
}

// On hosts without embedded helper binaries (darwin), Execute must stop at
// helper setup — but only after the helper config has been written, which
// pins the mode-selection wiring inside the full Execute path.
func TestExecuteStopsAtHelperExtractionWithoutEmbeddedBinaries(t *testing.T) {
	if helperBinariesEmbedded() {
		t.Skip("this host embeds helper binaries; the failure branch is unreachable (covered on darwin)")
	}
	requireTool(t, "bash")
	pinCroniumEnv(t)

	e, _ := newTestExecutor(t)
	t.Cleanup(func() { _ = e.Cleanup() })
	payloadPath := writeSignedPayload(t, []tarEntry{
		{name: "manifest.yaml", content: e2eManifest, mode: 0o644},
		{name: "script.sh", content: "echo never-runs\n", mode: 0o755},
	})

	err := e.Execute(payloadPath)
	if err == nil || !strings.Contains(err.Error(), "failed to setup helpers") {
		t.Fatalf("expected helper setup failure, got: %v", err)
	}

	configJSON, readErr := os.ReadFile(filepath.Join(e.workDir, ".cronium", "config.json"))
	if readErr != nil {
		t.Fatalf("expected helper config to be written before extraction failed: %v", readErr)
	}
	if !strings.Contains(string(configJSON), `"mode": "bundled"`) {
		t.Errorf("config.json = %s, want bundled mode", configJSON)
	}
}
