import { z } from "zod";
import {
  createTRPCRouter,
  protectedProcedure,
  withTiming,
  withRateLimit,
} from "../trpc";
import { TRPCError } from "@trpc/server";
import { withErrorHandling } from "@/server/utils/error-utils";
import {
  mutationResponse,
  resourceResponse,
} from "@/server/utils/api-patterns";
import { storage } from "@/server/storage";
import {
  generateScriptCode,
  isAiConfigured,
  listAvailableModels,
} from "@/lib/ai";
import { AI_PROVIDER_IDS } from "@/shared/ai-providers";

// Schemas
const generateScriptSchema = z.object({
  prompt: z.string().min(1, "Prompt is required"),
  scriptType: z.string(),
  currentCode: z.string().optional(),
});

// List the models a provider serves, for populating the model picker when a
// user configures a per-user AI connection. Mirrors admin.listAiModels but is
// available to any authenticated user (their own key travels in the POST body).
const listModelsSchema = z.object({
  provider: z.enum(AI_PROVIDER_IDS),
  apiKey: z.string().optional(),
  baseUrl: z.string().optional(),
});

export const aiRouter = createTRPCRouter({
  // Generate script code using AI
  generateScript: protectedProcedure
    .use(withTiming)
    .use(withRateLimit(10, 60000)) // 10 AI generations per minute per user
    .input(generateScriptSchema)
    .mutation(async ({ ctx, input }) => {
      return withErrorHandling(
        async () => {
          // Check if AI is enabled
          const aiEnabledSetting = await storage.getSetting("aiEnabled");
          if (aiEnabledSetting?.value !== "true") {
            throw new TRPCError({
              code: "FORBIDDEN",
              message: "AI script generation is not enabled",
            });
          }

          // Check if the configured AI provider has credentials
          if (!(await isAiConfigured())) {
            throw new TRPCError({
              code: "PRECONDITION_FAILED",
              message: "AI provider API key not configured",
            });
          }

          // Generate code with the configured provider
          const generatedCode = await generateScriptCode(
            input.prompt,
            input.scriptType,
            input.currentCode,
          );

          // Log the AI generation for audit purposes
          console.log(
            `AI script generated by user ${ctx.session.user.id} for script type ${input.scriptType}`,
          );

          return mutationResponse(
            { code: generatedCode },
            "Script generated successfully",
          );
        },
        {
          component: "aiRouter",
          operationName: "generateScript",
          userId: ctx.session.user.id,
        },
      );
    }),

  // List available models for an AI provider (for the per-user AI connection
  // form). A mutation so the API key travels in the POST body, not a GET URL.
  listModels: protectedProcedure
    .use(withTiming)
    .use(withRateLimit(30, 60000))
    .input(listModelsSchema)
    .mutation(async ({ ctx, input }) => {
      return withErrorHandling(
        async () => {
          const result = await listAvailableModels(
            input.provider,
            input.apiKey?.trim() ? input.apiKey.trim() : undefined,
            input.baseUrl?.trim() ? input.baseUrl.trim() : undefined,
          );
          return resourceResponse(result);
        },
        {
          component: "aiRouter",
          operationName: "listModels",
          userId: ctx.session.user.id,
        },
      );
    }),
});
